### PR TITLE
Enhance letsencrypt_service

### PR DESCRIPTION
**Pull request by JrCs**
Avoid 'ln: failed to create symbolic link' errors

### CODE REVIEW

**Comment by dmp1ce** [comment]
I merged up to 1ee83cc0f651dff9ab2dbc0bfd4e31f55d753fdb. I'm not sure how the other two commits "Fix multi-domain support". I was able to get multi-domain certificate working for a container and SNI working with two containers. For example, I had "example1.com" and "www.example1.com" on one container and "example2.com" on a second container, but resolving to the correct container using SNI.

I'll manually add in some other fixes you had in that commit though.

**Comment by JrCs** [comment]
For the multidomain, i have like you example.com and www.example.com, but before my patch it's only create one certificate and symlink the 2 domains to the same certificate. It didn't works because one of the domain doesn"t match the CN in the created certificate.

The _Enhance update of certificates_ commit is to avoid starting 2 docker-gen and to not wait for (at max) 3600s before creating/update a new certificate. If a new container with LETSENCRYPT_XXXX environment variable is start the certificate is automaticaly check then create/update after 10s.

**Comment by dmp1ce** [comment]
Thank you for the explanation. I didn't know there was an issue with CN. Also, I had never seen the trap loop before so I had to see for myself that it worked. Nice improvement!

**Comment by JrCs** [comment]
Thanks for you job, it's a big improvement !

**Pull request merged**
