### PR TITLE
Various fix

### PR DESCRIPTION
**Pull request by hadim**
Various fix:
- update README
- remove `build.sh` cuz it makes docker build starting from the beginning each time I call `docker build`
- add 

```
/usr/local/bin/docker-gen -only-exposed /app/nginx.tmpl /etc/nginx/conf.d/default.conf
nginx -s reload
```

when `$simp_le_return -eq 0` in `letsencrypt_service`.

I can't test it since `ERROR:simp_le: ACME server returned an error: rateLimited :: There were too many requests of a given type :: Error creating new cert :: Too many certificates already issued for: example.com`.

But I think it should fix it. If you see a better fix @dmp1ce, tell me.

### CODE REVIEW

**Comment by dmp1ce** [comment]
I think @JrCs may have had everything in build.sh to cut down on the image size. I'm not sure about that though.

I tend to agree that having all the steps in the Dockerfile is nicer for developing.

Everything else looks good. Thank you for adding the docker-gen regeneration. I'll probably merge later today.

**Comment by hadim** [comment]
Hum I don't think that `build.sh` will reduce **final** image size cuz at the end the same files are in the image. But for sure, users building with `build.sh` will have less **intermediates** images and then less size will be taken on the hard drive.

I don't think it's an issue cuz what is important is the **final** image size since most of the users don't build the image but will pull it directly from docker hub.

Cool if you can merge it but I would prefer you to test it if you can before (as I said I can't for now due to limitation from letsencrypt servers).

**Comment by dmp1ce** [comment]
Testing now. Do you want your name in the Dockerfile MAINTAINER? I'm going to add mine and remove jwilder.

**Comment by hadim** [comment]
Sure :-)

**Comment by hadim** [comment]
Maybe you can also remove the github link showing that it's a fork and add a message to the README saying it's a fork from `jwilder/nginx-proxy` and explaining the reason why you created it.

**Comment by dmp1ce** [comment]
All my tests passed.
- I deleted all my certificates and on the first run the certificates were downloaded and URL changed from http to https.
- I changed my valid_min time from 30 days to 100 days which causes simp_le to renew everytime it checks which correctly replaced the old certification.
- I had multiple domains on one VIRTUAL_HOST www. and non www and multiple VIRTUAL_HOST containers. That also passed.

Nice work!

I'll update the maintainers and add a brief explination in the README.

What is your email you want to use @hadim ?

**Comment by hadim** [comment]
You can use hadrien.mary@gmail.com

**Comment by JrCs** [comment]
Don't remove the build.sh.
It's the piece to reduce the image size.
If you don't use a script to build your image size will grow by 200Mo (git, python, gcc, and all the dependencies).
When you add something, add it after the build.sh in the dockerfile (so the build.sh will not be reexecuted every time) and when all is correct move the command from the dockerfile to the build.sh script

**Comment by hadim** [comment]
I don't understand because python will still be needed (and here) to execute `simp_le` ?

**Comment by JrCs** [comment]
About the issue your fix it's not correct.
To fix the issue we must recreate the nginx configuration with docker-gen if at least one certs have been create/updated.
The fix is in my todo list.

**Comment by hadim** [comment]
How do you check the image size ? Because `docker images` returns only the virtual size and it's different depending on the other image on your system.

**Comment by JrCs** [comment]
@hadim yes for python, but every time you use a RUN command it will create a new layer.
And so your final image wiil have layers with git, compiler (gcc), all tools to compile whith python (python-dev, python-pip), etc..

**Comment by hadim** [comment]
Sure and that is great when you use `docker build` but as I said most of the users will do a `docker pull` and so only download the final layer.

**Comment by hadim** [comment]
So the size won't change.

**Comment by JrCs** [comment]
With docker image and virtualsize. Virtual size is the sum of all the layer size.
Mine is only 224.1 MB, look at yours

**Comment by hadim** [comment]
`223.7 MB`. As I said the size will vary according to your system but if you use `docker pull` the size will be the same for everyone.

**Comment by hadim** [comment]
I don't understand why you say the fix is not correct ? I am updating the nginx config each time a new certificates is created. What is wrong with that ? What alternative do you propose ?

**Comment by hadim** [comment]
If you really want to reduce the number of layers, you can merge `RUN` commands on the `Dockerfile` (using `&&`). But I don't think using a script like `build.sh` is necessary. It add unecessary noise in my opinion.

**Comment by JrCs** [comment]
You don't need to create a new nginx config for each certificate that is created.
Only need to create a new nginx config if at least one certificate is create/update at the end of the letsencrypt_service.

About the image, the goal is to reduce the size of the image not the number of layers. So the goal is to have a smaller image size (the sum of all the layers to download).

To reduce the size/number of layers we can use RUN commands with && but it's harder to read and it's "difficult" to add conditionals in it. With a script it easier to write and read. The goal is not to use a SINGLE script to create the image, but one script that install a "functionality' (in our case: install simp_le program and it's dependancies)

**Comment by dmp1ce** [comment]
I'm fine either way with the build.sh step. A smaller 200MB smaller size probably is worth the change if that is the difference when the layers are added up.

I don't think @harim's solution to regenerating nginx configurations is wrong, it just isn't as efficient as it could be. It isn't being run in parrallel so if each certificate is updated then it will regenerate the configuration and restart nginx each time.

**Comment by dmp1ce** [comment]
Maybe something like this for the regeneration? I didn't test the code.

``` diff
diff --git a/letsencrypt_service b/letsencrypt_service
index 762be82..8ab1960 100755
--- a/letsencrypt_service
+++ b/letsencrypt_service
@@ -10,6 +10,7 @@ update_certs() {
     # Load relevant container settings
     source "$DIR"/letsencrypt_service_data

+    regenerate_nginx=false
     for cid in "${LETSENCRYPT_CONTAINERS[@]}"; do
         # Derive host and email variable names
         host_varname="LETSENCRYPT_${cid}_HOST"
@@ -38,11 +39,16 @@ update_certs() {
                 ln -sf ./$domain/key.pem       /etc/nginx/certs/$domain".key"

                 # Update certificates configuration in nginx
-                /usr/local/bin/docker-gen -only-exposed /app/nginx.tmpl /etc/nginx/conf.d/default.conf
-                nginx -s reload
+                regenerate_nginx=true
             fi
         done
     done
+
+    if [[ $regenerate_nginx ]]; then
+        /usr/local/bin/docker-gen -only-exposed /app/nginx.tmpl /etc/nginx/conf.d/default.conf
+        nginx -s reload
+    fi
+
     unset LETSENCRYPT_CONTAINERS
 }
```

**Comment by JrCs** [comment]
@dmp1ce seems ok. But use notify instead of call nginx -s reload every time because if the certificates didn't change we don't need to reload nginx

**Comment by hadim** [comment]
I agree that @dmp1ce solution is cleaner and more elegant but mine wasn't wrong.

About the size, I think that the use of `RUN`, `&&` and `\` is more readable than the `build.sh` solution. Now if you prefer the `build.sh` way both, go for it !

**Comment by dmp1ce** [comment]
@JrCs If the certificates change but the configuration does not, do we still need to `nginx -s reload`?

**Pull request merged**
